# Generated by Django 5.0.6 on 2024-06-02 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire_de_notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='ue',
        ),
        migrations.RemoveField(
            model_name='ressourceue',
            name='code',
        ),
        migrations.AddField(
            model_name='examen',
            name='ressource_ue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionnaire_de_notes.ressourceue'),
        ),
        migrations.AddField(
            model_name='ressourceue',
            name='code_ressource',
            field=models.CharField(default='default_code_ressource', max_length=30),
        ),
        migrations.AddField(
            model_name='ressourceue',
            name='enseignant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionnaire_de_notes.enseignant'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='groupe',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(upload_to='gestionnaire_de_notes/media/photo'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='examen',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='note',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire_de_notes.etudiant'),
        ),
        migrations.AlterField(
            model_name='note',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire_de_notes.examen'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ressourceue',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ressourceue',
            name='ue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionnaire_de_notes.ue'),
        ),
        migrations.AlterField(
            model_name='ue',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ue',
            name='credit_ects',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ue',
            name='nom',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ue',
            name='semestre',
            field=models.CharField(max_length=30),
        ),
    ]
